#!/bin/bash

if [ -z "$proxy_server" ]; then
    proxy_server="localhost:8888"
fi

echo_error() {
    echo $@ >&2
}

os=$(uname -s)
case $os in
    "Darwin")
        chrome_exec="/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"
        profile_hash=$(date +%s | md5)
        ;;
    "Linux")
        chrome_exec=$(which google-chrome)
        profile_hash=$(date +%s | md5sum | awk '{ print $1 }')
        ;;
    *)
        echo_error "Unknown operating system $os"
        exit 1
esac

if [ ! -e "$chrome_exec" ]; then
    echo_error "$chrome_exec doesn't exist"
    exit 1
elif [ ! -x "$chrome_exec" ]; then
    echo_error "$chrome_exec is not executable"
    exit 1
fi

user_data_dir="/tmp/chrome-profile-${profile_hash}"
log_path="/tmp/chrome-profile-${profile_hash}.log"
"$chrome_exec" $@ --proxy-server=$proxy_server --user-data-dir=$user_data_dir > $log_path 2>&1

