#!/bin/zsh

PWD=$(dirname $0)
if [ ! -f $PWD/antigen.zsh ]; then
    exit 1
fi

source $PWD/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle heroku
antigen bundle pip
antigen bundle lein
antigen bundle command-not-found

antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search

antigen apply
